#!/usr/bin/env python3
"""Generate the admin wireframes tab (D6, PLAN_admin_seed_v01.md section 14): docs/admin_wireframes.html plus the
public seed bundles it reads, docs/seed/<run>/admin/ for run-500 and run-3000 (GitHub Pages serves docs/ only; the
repo is private, but the bundle is written as a public-safe variant: no PAN, no dob, no legal_name, and every phone
number masked to "+91 9xxxx xx123" everywhere it appears in the seed).

Screens M02 to M14 are hand-authored in data/admin_screens.json (phase C part 1, 23 Sep 2026; this builder only
reads it). M01 (the bought stack) stays on the wireframes_v02.html tab. Three later agents write the per-screen
drawing code in scripts/admin_screens_1.js, _2.js, _3.js on top of the API in scripts/admin_core.js; this builder
includes whichever of those files exist and skips the rest.

Never hand-edit docs/. Called from scripts/build_site.py (import build_admin_wireframes; build_admin_wireframes.main())
after build_tracker.main(); also runs on its own.
"""
import json
import os
import sys

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPTS)
DATA = os.path.join(ROOT, "data")
DOCS = os.path.join(ROOT, "docs")
SEED_ROOT = os.path.join(ROOT, "seed")
SEED_DATA = os.path.join(DATA, "seed")
sys.path.insert(0, SCRIPTS)
import build_site as site  # noqa: E402
import validate_v02  # noqa: E402

RUNS = ["3000", "500"]
CHUNK_SIZE = 100
EXCLUDED_PEOPLE_FIELDS = ["pan", "dob", "legal_name"]
MASKED_FIELDS = ["phone"]

# Tables copied through unchanged (dict keyed by person_id, each value a list of rows) into tables.json.
PASSTHROUGH_TABLES = ["subscriptions", "payments", "plan_versions", "actions", "holdings", "aa_consents",
                      "cas_uploads", "ops_queue", "tasks", "tickets", "calls", "a_la_carte", "rpq", "covers"]
# Tables that go into every person's chunk entry, besides financial_records and events (person/NNNN.json).
CHUNK_TABLES = ["households", "reveal", "financial_records", "loans", "covers", "goals", "rpq", "nudges_sent",
                "state_flags"]
# Every table file read out of data/seed/<run>/ for counting and sourcing (people and staff handled separately).
ALL_SOURCE_TABLES = sorted(set(PASSTHROUGH_TABLES) | set(CHUNK_TABLES) | {"integration_events"})

ROLES = ["Principal officer", "Adviser", "Call centre", "Ops", "Marketing", "Compliance", "Support", "Finance"]
ROLE_VALUES = {"act", "read", "read, own people"}
TEMPLATES_F = {"T-tap", "T-num", "T-split", "T-list", "T-detail", "T-card", "T-card-stack", "T-hub", "T-review",
               "T-chart", "T-source", "T-upload", "T-progress", "T-webview", "T-sheet", "T-video", "T-paywall",
               "T-locked", "T-picker", "T-msg", "T-table"}


# ---------------------------------------------------------------- small helpers

def mask_phone(p):
    """"9000052984" -> "+91 9xxxx xx984": "+91 ", the first digit, "xxxx xx", the last three digits. Plain slicing."""
    return "+91 " + p[0] + "xxxx xx" + p[-3:]


def table_count(d):
    """Total rows for a dict-of-list-of-rows table, or the key count for a dict-of-one-row-per-person table."""
    total = 0
    for v in d.values():
        total += len(v) if isinstance(v, list) else 1
    return total


def read_anchor(run_dir):
    """The run's anchor, from the fixed first line of report.md: "Anchor <iso> (every date...". Plain prefix
    slicing (report.md is generated by scripts/seed_gen.py in this same repo, a closed machine format, not text
    parsed by a pattern rule); seed/config.json's own "anchor" block only carries the default rule ("run date"),
    not the concrete value used for this run, so report.md is the only place the actual anchor is recorded."""
    with open(os.path.join(run_dir, "report.md")) as fh:
        head = fh.read(600)
    for line in head.split("\n"):
        if line.startswith("Anchor "):
            return line[len("Anchor "):].split(" ", 1)[0]
    raise SystemExit("no 'Anchor ' line found in %s/report.md" % run_dir)


def load_table(run_dir, name):
    with open(os.path.join(run_dir, name + ".json")) as fh:
        return json.load(fh)


# ---------------------------------------------------------------- bundle: people, tables, assets, audit

def build_people(raw_people):
    """people.json: array sorted by person_id, without pan/dob/legal_name, phone masked."""
    out = []
    for pid in sorted(raw_people):
        rec = {k: v for k, v in raw_people[pid].items() if k not in EXCLUDED_PEOPLE_FIELDS}
        if rec.get("phone"):
            rec["phone"] = mask_phone(rec["phone"])
        out.append(rec)
    return out


def build_sip(financial_records):
    """{person_id: {value, value_kind, source, precision}} of each person's current_sip record (the M13 SIP book
    reads the AA-detected and typed SIPs without loading every person chunk)."""
    out = {}
    for pid, rows in financial_records.items():
        for row in rows:
            if row.get("field") == "current_sip":
                out[pid] = {"value": row.get("value"), "value_kind": row.get("value_kind"), "source": row.get("source"),
                            "precision": row.get("precision")}
    return out


def build_assets(financial_records, investable_fields):
    """{person_id: {field: number}} for every person with a financial record, over the investable field list."""
    out = {}
    for pid, rows in financial_records.items():
        assets = {}
        for row in rows:
            f = row.get("field")
            if f in investable_fields and row.get("value_kind") in ("exact", "band") and row.get("value") is not None:
                assets[f] = row["value"]
        out[pid] = assets
    return out


def stream_events(run_dir, wanted_types):
    """One pass over events.jsonl: per-person compact rows for the chunk files (signed_up.props.phone masked),
    plus the raw rows of the event types the audit log needs (so it never re-reads the file)."""
    by_person = {}
    by_type = {t: [] for t in wanted_types}
    path = os.path.join(run_dir, "events.jsonl")
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            e = json.loads(line)
            props = e.get("props") or {}
            if e["event"] == "signed_up" and props.get("phone"):
                props = dict(props)
                props["phone"] = mask_phone(props["phone"])
            by_person.setdefault(e["person_id"], []).append([e["at"], e["event"], e.get("screen_id"), props])
            if e["event"] in by_type:
                by_type[e["event"]].append(e)
    return by_person, by_type


AUDIT_WHO_SYSTEM = "system"
AUDIT_WHO_USER = "user"


def build_audit(tables, staff_by_id, by_type):
    """The M11 log: one row {at, person_id, record, action, who, detail} per regulated-record change found in the
    seed. Sourced from plan_versions/rpq/payments/aa_consents/calls/tasks/ops_queue rows and from the events of
    esign_done, plan_updated, update_accepted, payment_failed, aa_connected, aa_failed, cancelled and
    sharpen_saved. who is "user", "system" or a staff display name (call completions and resolved ops-queue items
    are attributed to the staff member on the row)."""
    rows = []

    def staff_name(sid):
        rec = staff_by_id.get(sid)
        return rec["name"] if rec else (sid or "system")

    for e in by_type.get("esign_done", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "agreement", "action": "signed",
                     "who": AUDIT_WHO_USER,
                     "detail": {"agreement_version": e["props"].get("agreement_version"),
                                "esign_ref": e["props"].get("esign_ref")}})

    for pid, rec in tables["rpq"].items():
        if rec.get("taken_at"):
            rows.append({"at": rec["taken_at"], "person_id": pid, "record": "risk_profile", "action": "taken",
                         "who": AUDIT_WHO_USER, "detail": {"risk_band": rec.get("risk_band")}})

    for pid, versions in tables["plan_versions"].items():
        for v in versions:
            if v.get("built_at"):
                rows.append({"at": v["built_at"], "person_id": pid, "record": "plan", "action": "built",
                             "who": AUDIT_WHO_SYSTEM,
                             "detail": {"plan_version": v.get("plan_version"),
                                        "assumptions_version": v.get("assumptions_version"),
                                        "instrument_set_version": v.get("instrument_set_version")}})
    for e in by_type.get("plan_updated", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "plan", "action": "updated",
                     "who": AUDIT_WHO_SYSTEM,
                     "detail": {"from_version": e["props"].get("from_version"), "to_version": e["props"].get("to_version"),
                                "reason": e["props"].get("reason")}})
    for e in by_type.get("update_accepted", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "plan", "action": "accepted",
                     "who": AUDIT_WHO_USER, "detail": {"to_version": e["props"].get("to_version")}})

    for pid, payments in tables["payments"].items():
        for p in payments:
            status = p.get("status")
            if status in ("captured", "refunded") and p.get("paid_at"):
                rows.append({"at": p["paid_at"], "person_id": pid, "record": "payment",
                             "action": status, "who": AUDIT_WHO_USER if status == "captured" else AUDIT_WHO_SYSTEM,
                             "detail": {"invoice_no": p.get("invoice_no"), "amount": p.get("amount")}})
    for e in by_type.get("payment_failed", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "payment", "action": "failed",
                     "who": AUDIT_WHO_SYSTEM, "detail": {"grace_until": e["props"].get("grace_until")}})
    for e in by_type.get("cancelled", []):
        if e["props"].get("refund_requested"):
            rows.append({"at": e["at"], "person_id": e["person_id"], "record": "payment", "action": "refund_requested",
                         "who": AUDIT_WHO_USER, "detail": {"reason": e["props"].get("reason")}})

    for e in by_type.get("aa_connected", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "aa_consent", "action": "connected",
                     "who": AUDIT_WHO_USER,
                     "detail": {"institutions_ok": e["props"].get("institutions_ok"),
                                "institutions_failed": e["props"].get("institutions_failed")}})
    for e in by_type.get("aa_failed", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "aa_consent", "action": "failed",
                     "who": AUDIT_WHO_SYSTEM,
                     "detail": {"institutions_ok": e["props"].get("institutions_ok"),
                                "institutions_failed": e["props"].get("institutions_failed")}})
    for pid, consents in tables["aa_consents"].items():
        for c in consents:
            if c.get("renewed_at"):
                rows.append({"at": c["renewed_at"], "person_id": pid, "record": "aa_consent", "action": "renewed",
                             "who": AUDIT_WHO_USER, "detail": {"consent_expiry": c.get("consent_expiry")}})
            if c.get("status") == "expired" and c.get("consent_expiry"):
                rows.append({"at": c["consent_expiry"], "person_id": pid, "record": "aa_consent", "action": "expired",
                             "who": AUDIT_WHO_SYSTEM, "detail": {}})

    for pid, calls in tables["calls"].items():
        for c in calls:
            if c.get("status") == "completed" and c.get("input_changes") and c.get("slot"):
                rows.append({"at": c["slot"], "person_id": pid, "record": "call", "action": "completed",
                             "who": staff_name(c.get("adviser_id")), "detail": {"input_changes": c["input_changes"]}})

    for pid, tasks in tables["tasks"].items():
        for t in tasks:
            if t.get("state_id") == "S25":
                fields = t.get("fields") or {}
                at = fields.get("requested_at") or t.get("created_at")
                if at:
                    rows.append({"at": at, "person_id": pid, "record": "deletion", "action": "requested",
                                 "who": AUDIT_WHO_USER, "detail": {"records_retained": fields.get("records_retained")}})

    for pid, items in tables["ops_queue"].items():
        for it in items:
            if it.get("status") == "resolved" and it.get("resolved_at"):
                rows.append({"at": it["resolved_at"], "person_id": pid, "record": "ops_queue", "action": "resolved",
                             "who": staff_name(it.get("owner")), "detail": {"type": it.get("type"), "detail": it.get("detail")}})

    for e in by_type.get("sharpen_saved", []):
        rows.append({"at": e["at"], "person_id": e["person_id"], "record": "financial_record", "action": "sharpened",
                     "who": AUDIT_WHO_USER, "detail": {"field": e["props"].get("field")}})

    rows.sort(key=lambda r: (r["at"], r["person_id"], r["record"], r["action"]))
    counts = {}
    for r in rows:
        counts[r["record"]] = counts.get(r["record"], 0) + 1
    return rows, counts


# ---------------------------------------------------------------- bundle assembly per run

def build_bundle(run, investable_fields):
    run_dir = os.path.join(SEED_DATA, "run-" + run)
    out_dir = os.path.join(DOCS, "seed", "run-" + run, "admin")
    os.makedirs(os.path.join(out_dir, "person"), exist_ok=True)

    raw_people = load_table(run_dir, "people")
    raw_staff = load_table(run_dir, "staff")
    app_config = load_table(run_dir, "config")

    tables_src = {name: load_table(run_dir, name) for name in ALL_SOURCE_TABLES}
    audit_event_types = ["esign_done", "plan_updated", "update_accepted", "payment_failed", "aa_connected",
                          "aa_failed", "cancelled", "sharpen_saved"]
    events_by_person, events_by_type = stream_events(run_dir, audit_event_types)

    people_ids_sorted = sorted(raw_people)
    people_bundle = build_people(raw_people)
    staff_bundle = [raw_staff[k] for k in sorted(raw_staff)]
    staff_by_id = raw_staff

    assets = build_assets(tables_src["financial_records"], investable_fields)
    audit_rows, audit_counts = build_audit(tables_src, staff_by_id, events_by_type)

    tables_json = {"staff": staff_bundle, "config": app_config, "assets": assets, "audit": audit_rows,
                   "sip": build_sip(tables_src["financial_records"])}
    for name in PASSTHROUGH_TABLES:
        tables_json[name] = tables_src[name]

    # person chunks, 100 per file, in person_id order
    n_chunks = (len(people_ids_sorted) + CHUNK_SIZE - 1) // CHUNK_SIZE if people_ids_sorted else 0
    chunk_files = {}
    for idx in range(n_chunks):
        chunk_ids = people_ids_sorted[idx * CHUNK_SIZE:(idx + 1) * CHUNK_SIZE]
        chunk = {}
        for pid in chunk_ids:
            entry = {}
            for name in CHUNK_TABLES:
                entry[name] = tables_src[name].get(pid, [] if name not in ("households", "reveal", "covers", "rpq", "state_flags") else {})
            entry["events"] = events_by_person.get(pid, [])
            chunk[pid] = entry
        chunk_files["%04d" % idx] = chunk

    anchor = read_anchor(run_dir)
    counts = {"people": len(people_bundle), "staff": len(staff_bundle), "assets": len(assets),
              "audit": len(audit_rows)}
    for name in ALL_SOURCE_TABLES:
        counts[name] = table_count(tables_src[name])
    meta = {"run": run, "anchor": anchor, "seed": 20260922, "counts": counts, "chunk_size": CHUNK_SIZE,
            "chunks": n_chunks, "excluded": list(EXCLUDED_PEOPLE_FIELDS), "masked": list(MASKED_FIELDS)}

    files = {
        "meta.json": meta,
        "people.json": people_bundle,
        "tables.json": tables_json,
        "integration_events.json": tables_src["integration_events"],
    }
    for name, chunk in chunk_files.items():
        files["person/%s.json" % name] = chunk

    written = {}
    for rel, obj in files.items():
        text = json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        path = os.path.join(out_dir, rel)
        with open(path, "w") as fh:
            fh.write(text)
        written[rel] = text

    # minimisation: no PAN, no raw phone (every person, not just paid) anywhere in any written file; ASCII everywhere.
    # Source scan (both runs) found exactly two places carrying a raw phone: people.<id>.phone, and the
    # signed_up event's props.phone; both are masked above before any file is written. This scan is the safety net.
    pans = {v["pan"] for v in raw_people.values() if v.get("pan")}
    phones = {v["phone"] for v in raw_people.values() if v.get("phone")}
    leaks = []
    for rel, text in written.items():
        for pan in pans:
            if pan in text:
                leaks.append("%s: PAN %s" % (rel, pan))
        for phone in phones:
            if phone in text:
                leaks.append("%s: raw phone %s" % (rel, phone))
        for ch in text:
            if ord(ch) > 126:
                leaks.append("%s: non-ASCII character" % rel)
                break
    if leaks:
        raise SystemExit("admin bundle minimisation scan failed:\n" + "\n".join(leaks[:40]))

    return {
        "run": run, "anchor": anchor, "counts": counts, "audit_counts": audit_counts,
        "bytes": {rel: len(text) for rel, text in written.items()},
    }


# ---------------------------------------------------------------- data/admin_screens.json validation

def load_admin_screens():
    with open(os.path.join(DATA, "admin_screens.json")) as fh:
        return json.load(fh)


def all_text(obj):
    out = []

    def walk(o):
        if isinstance(o, str):
            out.append(o)
        elif isinstance(o, list):
            for x in o:
                walk(x)
        elif isinstance(o, dict):
            for v in o.values():
                walk(v)

    walk(obj)
    return out


def validate_admin_screens(doc, wireframe_ids, vendor_names):
    p = []
    screens = doc.get("screens", [])
    ids = [s.get("id") for s in screens]
    expected_ids = ["M%02d" % n for n in range(2, 15)]
    if sorted(x for x in ids if x) != sorted(expected_ids) or len(ids) != len(set(ids)):
        p.append("screen ids are not exactly M02 to M14, one each: got %s" % ids)

    admin_ids = set(ids)
    for s in screens:
        sid = s.get("id", "?")
        for key in ("id", "sec", "title", "tier", "frame", "template", "path", "purpose", "ui", "events",
                    "compliance", "freeze", "v02", "spec", "seat", "role", "built", "writes", "zoho_instead"):
            if key not in s:
                p.append("%s: missing %s" % (sid, key))
        if s.get("template") not in TEMPLATES_F:
            p.append("%s: template %r not in the 21 appendix-F templates" % (sid, s.get("template")))
        if s.get("path") not in ("both", "aa", "manual"):
            p.append("%s: path %r" % (sid, s.get("path")))
        events = s.get("events") or []
        if (sid + "_view") not in events:
            p.append("%s: events missing %s_view" % (sid, sid))
        c = s.get("compliance") or {}
        if not isinstance(c.get("review"), bool) or not c.get("reasons"):
            p.append("%s: compliance flag incomplete" % sid)
        f = s.get("freeze") or {}
        if f.get("status") != "open" or not f.get("reason"):
            p.append("%s: freeze is not open with a reason" % sid)
        v = s.get("v02") or {}
        if not v.get("causes"):
            p.append("%s: v02 has no causes" % sid)
        spec = s.get("spec") or {}
        for key in ("fields", "logic", "branches", "states", "dev"):
            if key not in spec:
                p.append("%s: spec missing %s" % (sid, key))

        role = s.get("role") or {}
        for k, v2 in role.items():
            if k not in ROLES:
                p.append("%s: role key %r is not one of the eight roles" % (sid, k))
            if v2 not in ROLE_VALUES:
                p.append("%s: role %r value %r is not act, read or 'read, own people'" % (sid, k, v2))
        writes = s.get("writes") or []
        write_events = set()
        for w in writes:
            if not w.get("action") or not w.get("event") or not w.get("roles"):
                p.append("%s: writes entry missing action, event or roles: %r" % (sid, w))
                continue
            write_events.add(w["event"])
            for r in w["roles"]:
                if r not in ROLES:
                    p.append("%s: writes role %r is not one of the eight roles" % (sid, r))
        missing = write_events - set(events)
        if missing:
            p.append("%s: writes events not listed in events: %s" % (sid, sorted(missing)))

        for label, target in spec.get("branches", []):
            if target not in admin_ids and target not in wireframe_ids:
                p.append("%s: branch %r -> %s is neither an admin screen nor a wireframes screen" % (sid, label, target))

    texts = all_text(doc)
    for txt in texts:
        for name in validate_v02.NAMES_UI:
            if validate_v02.word_hit(txt, name):
                p.append("data/admin_screens.json: team name %s in text: %r" % (name, txt[:70]))
        for vendor in vendor_names:
            if vendor and vendor in txt:
                p.append("data/admin_screens.json: vendor name %s in text: %r" % (vendor, txt[:70]))
    for txt in texts:
        for ch in txt:
            if ord(ch) > 126:
                p.append("data/admin_screens.json: non-ASCII in %r" % txt[:60])
                break
    return p


# ---------------------------------------------------------------- the page

ADMIN_CSS = """
  .abar select,.abar input{padding:6px 8px;border:1px solid var(--line);border-radius:6px;background:#fff}
  .abar .a-note{color:var(--mute);font-size:12px}
  .a-top{border:1px solid var(--line);border-radius:8px;padding:8px 10px;margin:0 0 14px;background:#FCFCFD}
  .a-line{font-size:12.5px;margin:3px 0}
  .a-line b{font-weight:600;margin-right:4px}
  .w-table-wide{overflow-x:auto;margin:0 0 14px}
  .w-table-wide .w-table{margin:0;min-width:640px}
  .w-badge.ok{border-color:#3E7A4F;color:#3E7A4F}
  .w-badge.warn{border-color:#C9A800;color:#7A6000}
  .w-badge.bad{border-color:#8A2E2E;color:#8A2E2E}
"""

ADMIN_SCREEN_FILES = ["admin_screens_1.js", "admin_screens_2.js", "admin_screens_3.js"]


def build_page(admin_doc, states, admin_crm, anchor_text):
    who = '<div class="who">Reviewing as <select id="reviewer"></select></div>'
    bar = ('<div class="bar abar">'
           '<label>Run <select id="arun"><option value="3000">3,000 people</option><option value="500">500 people</option></select></label>'
           '<label>Person <input id="aperson" list="apeople" placeholder="search a person" autocomplete="off"><datalist id="apeople"></datalist></label>'
           '<span class="a-note">Synthetic people, seed 20260922, anchor %s. M01, the bought stack, stays on the '
           '<a href="wireframes_v02.html#M01">wireframes tab</a>.</span>' + site.seed_subnav("admin_wireframes.html") + '</div>\n'
           '<div class="banner">Every person here is synthetic. Write actions are mock; only comments are recorded.</div>\n'
           ) % site.esc(anchor_text)
    layout = site.WIRE_LAYOUT
    wire_opts = {"page": "admin_wireframes", "key": "yeslyf_admin_wire_v01", "version": "admin v0.1",
                 "exportTitle": "# yeslyf admin wireframes v0.1 - review comments",
                 "exportFile": "yeslyf_admin_wireframes_review_v01.md"}
    admin_runs = {"3000": "seed/run-3000/admin/", "500": "seed/run-500/admin/"}
    data = ('<script>var SECTIONS=' + site.js_blob(admin_doc["sections"]) + ';\nvar SCREENS=' + site.js_blob(admin_doc["screens"]) +
            ';\nvar DROPPED=' + site.js_blob([]) + ';\nvar SPLIT=' + site.js_blob([]) + ';\nvar STATES=' + site.js_blob([]) +
            ';\nvar REASONS=' + site.js_blob({}) + ';\nvar INTEGRATIONS=' + site.js_blob(site.integrations_blob()) +
            ';\nvar FREEZE=' + site.js_blob(None) + ';\nvar WIRE_OPTS=' + site.js_blob(wire_opts) +
            ';\nvar ADMIN_RUNS=' + site.js_blob(admin_runs) + ';\nvar ADMIN_STATES=' + site.js_blob(states["states"] if states else []) +
            ';\nvar ADMIN_PLACEMENT=' + site.js_blob(admin_crm.get("PLACEMENT", [])) + ';</script>\n')
    scripts = [site.store_script(), '<script>' + site.read_script("renderer_v02.js") + '</script>\n',
               '<script>' + site.read_script("admin_core.js") + '</script>\n']
    for name in ADMIN_SCREEN_FILES:
        path = os.path.join(SCRIPTS, name)
        if os.path.exists(path):
            scripts.append('<script>' + site.read_script(name) + '</script>\n')
    page = (site.head("yeslyf admin wireframes v0.1", site.read_script("renderer_v02.css") + site.SUBNAV_CSS + ADMIN_CSS) + '<body>\n' +
            site.header("admin_wireframes.html", "admin wireframes v0.1, 13 screens over the seed", who_html=who,
                        export_label="Export comments") +
            bar + layout + data + "".join(scripts) + '</body>\n</html>\n')
    return page


def anchor_display(iso):
    months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    d = iso[:10].split("-")
    if len(d) != 3:
        return iso
    y, m, day = d
    return "%d %s %s" % (int(day), months[int(m) - 1], y)


# ---------------------------------------------------------------- main

def main():
    admin_doc = load_admin_screens()
    v02 = site.load("screens_v02.json")
    wireframe_ids = {s["id"] for s in v02["screens"]}
    integ_rows = site.load("integrations.json")["rows"]
    # Vendor strings to ban from screen text, minus the placeholder-status labels a few rows carry ("internal",
    # "internal (Spinach)", "not decided", I13/I19/I20/I23/I24): those are not vendor names, and "internal" is
    # also the established compliance reason category used on every M-series screen (data/compliance_reasons.json).
    generic_vendor_labels = {"internal", "internal (Spinach)", "not decided"}
    vendor_names = [r["vendor"] for r in integ_rows if r["vendor"] not in generic_vendor_labels]
    states = site.load_optional("v02", "states.json")
    admin_crm = site.load("admin_crm.json")

    problems = validate_admin_screens(admin_doc, wireframe_ids, vendor_names)
    if problems:
        for x in problems[:60]:
            print("ERROR: " + x)
        if len(problems) > 60:
            print("ERROR: ... %d more" % (len(problems) - 60))
        sys.exit(1)

    with open(os.path.join(SEED_ROOT, "config.json")) as fh:
        gen_cfg = json.load(fh)
    investable_fields = gen_cfg["fields"]["investable"]

    reports = []
    for run in RUNS:
        reports.append(build_bundle(run, investable_fields))

    anchors = {r["anchor"] for r in reports}
    anchor_iso = sorted(anchors)[0]

    page = build_page(admin_doc, states, admin_crm, anchor_display(anchor_iso))
    site.check_ascii("admin_wireframes.html", page)
    page_problems = []
    if 'name="robots" content="noindex' not in page:
        page_problems.append("admin_wireframes.html lacks noindex")
    for word in site.FORBIDDEN:
        i = page.find(word)
        while i >= 0:
            page_problems.append("admin_wireframes.html contains %r: ...%s..." % (word, page[max(0, i - 50):i + len(word) + 30].replace("\n", " ")))
            i = page.find(word, i + 1)
    if page_problems:
        for x in page_problems:
            print("ERROR: " + x)
        sys.exit(1)

    with open(os.path.join(DOCS, "admin_wireframes.html"), "w") as fh:
        fh.write(page)
    print("wrote docs/admin_wireframes.html (%d bytes)" % len(page))

    for r in reports:
        total_bytes = sum(r["bytes"].values())
        print("run-%s admin bundle: %d files, %d bytes total, anchor %s" % (r["run"], len(r["bytes"]), total_bytes, r["anchor"]))
        print("  counts: %s" % json.dumps(r["counts"], sort_keys=True))
        print("  audit rows by record: %s" % json.dumps(r["audit_counts"], sort_keys=True))
    print("phone masking: people.phone and the signed_up event's props.phone (the only two carriers found in the "
          "seed); minimisation scan confirms no raw phone or PAN survives in any bundle file.")


if __name__ == "__main__":
    main()
